### ISSUE TITLE
Adjust scopes to be shared across roles

### ISSUE THREAD

**Issue by jamesduncan** [appdevdesigns/app_builder#97] opened 2020-06-04 06:47 UTC
Right now the scopes are created and stored to only be used on a single role. Can we adjust it so the same scope can be used across multiple roles?

**Comment by wongpratan** [comment] 2020-09-03 03:45
![share scopes](https://user-images.githubusercontent.com/545045/92068976-77614580-edd2-11ea-9bef-4c24fb94af33.png)
There is import exists scope feature.

**Comment by Achoobert** [comment] 2020-09-03 03:56
> There is import exists scope feature.

it used to 'steal' the scope from the old role. It looks like this make be fixed now?

**Comment by nh758** [comment] 2020-09-07 04:30
This still exists.
**Reproduce:**
1. Add a Scope A to Role 1
1. Import Scope A from Role 2
2. Reload AppBuilder
2. Check Role 1 and see no Scope A

**Expected Behavior:**
Role 1 still has Scope A, Role 2 also has Scope A

**Closed** 2020-09-15 09:25 UTC
Labels: enhancement
